modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="minecraft_rewind"
version="1.0.0"
displayName="Minecraft: Rewind"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Credits | MCreator - Tools | BBB Disocrd - Ideas | LoxyTheReindeer - Model for Romeo's Glock |"
authors="PAK-VIN & SmartPixel Studios"
description="The story mode you know and love, rewinded."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minecraft_rewind]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minecraft_rewind]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration