modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="minecraft_rewind_forge"
version="1.0.0"
displayName="Minecraft: Rewind - Forge Edition"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Credits | MCreator - Tools | BBB Disocrd - Ideas | LoxyTheReindeer - Model for Romeo's Glock |"
authors="PAK-VIN & SmartPixel Studios"
description="The story mode you know and love, rewinded."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minecraft_rewind_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration